parameters:
    database_driver: pdo_mysql
    database_host: localhost
    database_port: null
    database_name: polly
    database_user: root
    database_password: mio
    mailer_transport: smtp
    mailer_host: localhost
    mailer_user: null
    mailer_password: null
    locale: en
    secret: 7257fb4dd5cbbe2279103c35b62cea8c5
    database_path: null
